INSERT INTO country (id_country,name) VALUES (1,'Colombia');
INSERT INTO country (id_country,name) VALUES (2,'Peru');
INSERT INTO country (id_country,name) VALUES (3,'Mexico');
INSERT INTO country (id_country,name) VALUES (4,'Argentina');
INSERT INTO country (id_country,name) VALUES (5,'Ecuador');
INSERT INTO country (id_country,name) VALUES (6,'Nicaragua');
INSERT INTO country (id_country,name) VALUES (7,'Venezuela');
INSERT INTO country (id_country,name) VALUES (8,'Bolivia');
INSERT INTO country (id_country,name) VALUES (9,'Costa Rica');
INSERT INTO country (id_country,name) VALUES (10,'Cuba');
INSERT INTO country (id_country,name) VALUES (11,'Belize');
INSERT INTO country (id_country,name) VALUES (12,'Cuba');
INSERT INTO country (id_country,name) VALUES (13,'Saudi Arabia');
INSERT INTO country (id_country,name) VALUES (14,'Palestine, State of');
INSERT INTO country (id_country,name) VALUES (15,'Turks and Caicos Islands');
INSERT INTO country (id_country,name) VALUES (16,'Somalia');
INSERT INTO country (id_country,name) VALUES (17,'Belarus');
INSERT INTO country (id_country,name) VALUES (18,'Malta');
INSERT INTO country (id_country,name) VALUES (19,'Liechtenstein');
INSERT INTO country (id_country,name) VALUES (20,'Cambodia');
INSERT INTO country (id_country,name) VALUES (21,'Guadeloupe');
INSERT INTO country (id_country,name) VALUES (22,'Åland Islands');
INSERT INTO country (id_country,name) VALUES (23,'Cyprus');
INSERT INTO country (id_country,name) VALUES (24,'Bhutan');
INSERT INTO country (id_country,name) VALUES (25,'Turks and Caicos Islands');
INSERT INTO country (id_country,name) VALUES (26,'Libya');
INSERT INTO country (id_country,name) VALUES (27,'Ireland');
INSERT INTO country (id_country,name) VALUES (28,'Pakistan');
INSERT INTO country (id_country,name) VALUES (29,'Comoros');
INSERT INTO country (id_country,name) VALUES (30,'Puerto Rico');
INSERT INTO country (id_country,name) VALUES (31,'Ecuador');
INSERT INTO country (id_country,name) VALUES (32,'Nepal');
INSERT INTO country (id_country,name) VALUES (33,'Argentina');
INSERT INTO country (id_country,name) VALUES (34,'Austria');
INSERT INTO country (id_country,name) VALUES (35,'Jersey');
INSERT INTO country (id_country,name) VALUES (36,'Micronesia');
INSERT INTO country (id_country,name) VALUES (37,'Brunei');
INSERT INTO country (id_country,name) VALUES (38,'Eritrea');
INSERT INTO country (id_country,name) VALUES (39,'Norway');
INSERT INTO country (id_country,name) VALUES (40,'French Polynesia');
INSERT INTO country (id_country,name) VALUES (41,'American Samoa');
INSERT INTO country (id_country,name) VALUES (42,'Nicaragua');
INSERT INTO country (id_country,name) VALUES (43,'Tajikistan');
INSERT INTO country (id_country,name) VALUES (44,'Saint Barthélemy');
INSERT INTO country (id_country,name) VALUES (45,'Cyprus');
INSERT INTO country (id_country,name) VALUES (46,'Zambia');
INSERT INTO country (id_country,name) VALUES (47,'Dominica');
INSERT INTO country (id_country,name) VALUES (48,'French Southern Territories');
INSERT INTO country (id_country,name) VALUES (49,'Honduras');
INSERT INTO country (id_country,name) VALUES (50,'Ukraine');
INSERT INTO country (id_country,name) VALUES (51,'Saint Martin');
INSERT INTO country (id_country,name) VALUES (52,'Thailand');
INSERT INTO country (id_country,name) VALUES (53,'Kuwait');
INSERT INTO country (id_country,name) VALUES (54,'Liechtenstein');
INSERT INTO country (id_country,name) VALUES (55,'Sweden');
INSERT INTO country (id_country,name) VALUES (56,'Togo');
INSERT INTO country (id_country,name) VALUES (57,'Namibia');
INSERT INTO country (id_country,name) VALUES (58,'Norway');
INSERT INTO country (id_country,name) VALUES (59,'Korea, South');
INSERT INTO country (id_country,name) VALUES (60,'United States Minor Outlying Islands');
INSERT INTO country (id_country,name) VALUES (61,'Virgin Islands, United States');
INSERT INTO country (id_country,name) VALUES (62,'Svalbard and Jan Mayen Islands');
INSERT INTO country (id_country,name) VALUES (63,'Cocos (Keeling) Islands');
INSERT INTO country (id_country,name) VALUES (64,'Pitcairn Islands');
INSERT INTO country (id_country,name) VALUES (65,'French Guiana');
INSERT INTO country (id_country,name) VALUES (66,'Azerbaijan');
INSERT INTO country (id_country,name) VALUES (67,'Moldova');
INSERT INTO country (id_country,name) VALUES (68,'Afghanistan');
INSERT INTO country (id_country,name) VALUES (69,'Switzerland');
INSERT INTO country (id_country,name) VALUES (70,'Georgia');
INSERT INTO country (id_country,name) VALUES (71,'Palau');
INSERT INTO country (id_country,name) VALUES (72,'Mayotte');
INSERT INTO country (id_country,name) VALUES (73,'France');
INSERT INTO country (id_country,name) VALUES (74,'Indonesia');
INSERT INTO country (id_country,name) VALUES (75,'Sri Lanka');
INSERT INTO country (id_country,name) VALUES (76,'Gambia');
INSERT INTO country (id_country,name) VALUES (77,'Kuwait');
INSERT INTO country (id_country,name) VALUES (78,'Colombia');
INSERT INTO country (id_country,name) VALUES (79,'Isle of Man');
INSERT INTO country (id_country,name) VALUES (80,'Cape Verde');
INSERT INTO country (id_country,name) VALUES (81,'Cuba');
INSERT INTO country (id_country,name) VALUES (82,'Kazakhstan');
INSERT INTO country (id_country,name) VALUES (83,'Mozambique');
INSERT INTO country (id_country,name) VALUES (84,'Thailand');
INSERT INTO country (id_country,name) VALUES (85,'Canada');
INSERT INTO country (id_country,name) VALUES (86,'Brazil');
INSERT INTO country (id_country,name) VALUES (87,'Malta');
INSERT INTO country (id_country,name) VALUES (88,'Saint Lucia');
INSERT INTO country (id_country,name) VALUES (89,'Slovenia');
INSERT INTO country (id_country,name) VALUES (90,'Mayotte');
INSERT INTO country (id_country,name) VALUES (91,'Dominican Republic');
INSERT INTO country (id_country,name) VALUES (92,'Belgium');
INSERT INTO country (id_country,name) VALUES (93,'Slovenia');
INSERT INTO country (id_country,name) VALUES (94,'Palestine, State of');
INSERT INTO country (id_country,name) VALUES (95,'Rwanda');
INSERT INTO country (id_country,name) VALUES (96,'Grenada');
INSERT INTO country (id_country,name) VALUES (97,'Aruba');
INSERT INTO country (id_country,name) VALUES (98,'Gabon');
INSERT INTO country (id_country,name) VALUES (99,'Germany');
INSERT INTO country (id_country,name) VALUES (100,'Heard Island and Mcdonald Islands');