INSERT INTO product (id_product,name,price,description) VALUES (101,'Lorem',1160,'nonummy ipsum non arcu. Vivamus');
INSERT INTO product (id_product,name,price,description) VALUES (102,'dolor',689,'nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam');
INSERT INTO product (id_product,name,price,description) VALUES (103,'Aenean',353,'ut ipsum');
INSERT INTO product (id_product,name,price,description) VALUES (104,'dolor.',592,'elit. Curabitur');
INSERT INTO product (id_product,name,price,description) VALUES (105,'sociis',1169,'gravida molestie');
INSERT INTO product (id_product,name,price,description) VALUES (106,'lectus,',1014,'laoreet ipsum. Curabitur consequat, lectus sit amet luctus');
INSERT INTO product (id_product,name,price,description) VALUES (107,'orci,',397,'pellentesque eget, dictum placerat, augue. Sed molestie. Sed');
INSERT INTO product (id_product,name,price,description) VALUES (108,'faucibus',680,'semper, dui lectus rutrum urna, nec luctus');
INSERT INTO product (id_product,name,price,description) VALUES (109,'augue,',900,'Aliquam tincidunt, nunc ac mattis ornare, lectus ante');
INSERT INTO product (id_product,name,price,description) VALUES (110,'urna',654,'Vivamus euismod urna. Nullam lobortis');
INSERT INTO product (id_product,name,price,description) VALUES (111,'justo.',513,'faucibus orci luctus et ultrices posuere');
INSERT INTO product (id_product,name,price,description) VALUES (112,'morbi',1139,'sodales purus, in molestie tortor nibh sit amet orci. Ut');
INSERT INTO product (id_product,name,price,description) VALUES (113,'dis',653,'eu erat semper rutrum. Fusce dolor quam,');
INSERT INTO product (id_product,name,price,description) VALUES (114,'Curabitur',718,'fames ac turpis');
INSERT INTO product (id_product,name,price,description) VALUES (115,'velit',847,'libero. Morbi accumsan');
INSERT INTO product (id_product,name,price,description) VALUES (116,'Pellentesque',802,'Sed nunc est, mollis');
INSERT INTO product (id_product,name,price,description) VALUES (117,'Quisque',529,'ipsum. Suspendisse sagittis. Nullam');
INSERT INTO product (id_product,name,price,description) VALUES (118,'Etiam',201,'Nam ac');
INSERT INTO product (id_product,name,price,description) VALUES (119,'Fusce',900,'nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce');
INSERT INTO product (id_product,name,price,description) VALUES (120,'in,',1188,'Morbi accumsan laoreet');
INSERT INTO product (id_product,name,price,description) VALUES (121,'enim',777,'natoque penatibus et magnis dis parturient montes, nascetur');
INSERT INTO product (id_product,name,price,description) VALUES (122,'nec',424,'Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque');
INSERT INTO product (id_product,name,price,description) VALUES (123,'lorem',869,'vitae, orci. Phasellus dapibus quam quis');
INSERT INTO product (id_product,name,price,description) VALUES (124,'nunc',716,'nulla magna,');
INSERT INTO product (id_product,name,price,description) VALUES (125,'neque.',1081,'sem. Nulla interdum. Curabitur dictum. Phasellus in');
INSERT INTO product (id_product,name,price,description) VALUES (126,'ipsum',634,'et libero. Proin mi. Aliquam gravida mauris');
INSERT INTO product (id_product,name,price,description) VALUES (127,'eros',259,'magna. Suspendisse tristique neque');
INSERT INTO product (id_product,name,price,description) VALUES (128,'Integer',927,'mi. Duis risus');
INSERT INTO product (id_product,name,price,description) VALUES (129,'ornare,',1037,'In');
INSERT INTO product (id_product,name,price,description) VALUES (130,'Curabitur',1022,'aliquet libero. Integer');
INSERT INTO product (id_product,name,price,description) VALUES (131,'a,',528,'a, facilisis non,');
INSERT INTO product (id_product,name,price,description) VALUES (132,'dui',1185,'ipsum.');
INSERT INTO product (id_product,name,price,description) VALUES (133,'Nullam',781,'enim,');
INSERT INTO product (id_product,name,price,description) VALUES (134,'Donec',194,'leo. Morbi neque tellus, imperdiet non, vestibulum nec,');
INSERT INTO product (id_product,name,price,description) VALUES (135,'Duis',107,'lorem ac risus. Morbi metus. Vivamus');
INSERT INTO product (id_product,name,price,description) VALUES (136,'Ut',503,'velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer');
INSERT INTO product (id_product,name,price,description) VALUES (137,'justo',569,'enim nisl');
INSERT INTO product (id_product,name,price,description) VALUES (138,'ac,',362,'eu arcu. Morbi sit amet massa. Quisque porttitor eros');
INSERT INTO product (id_product,name,price,description) VALUES (139,'dui',233,'lacinia.');
INSERT INTO product (id_product,name,price,description) VALUES (140,'odio.',129,'facilisis non,');
INSERT INTO product (id_product,name,price,description) VALUES (141,'Aliquam',254,'lorem ac risus. Morbi metus. Vivamus euismod urna.');
INSERT INTO product (id_product,name,price,description) VALUES (142,'mus.',457,'nostra, per inceptos hymenaeos. Mauris ut');
INSERT INTO product (id_product,name,price,description) VALUES (143,'pellentesque',698,'urna. Nullam lobortis quam a felis ullamcorper');
INSERT INTO product (id_product,name,price,description) VALUES (144,'Aliquam',1192,'Duis ac arcu. Nunc mauris. Morbi');
INSERT INTO product (id_product,name,price,description) VALUES (145,'elit,',836,'scelerisque');
INSERT INTO product (id_product,name,price,description) VALUES (146,'et',762,'blandit');
INSERT INTO product (id_product,name,price,description) VALUES (147,'eget',1017,'sem egestas blandit. Nam');
INSERT INTO product (id_product,name,price,description) VALUES (148,'fringilla,',347,'fermentum vel, mauris. Integer sem elit,');
INSERT INTO product (id_product,name,price,description) VALUES (149,'dictum.',1109,'elementum sem,');
INSERT INTO product (id_product,name,price,description) VALUES (150,'interdum.',1115,'facilisis, magna tellus faucibus leo,');
INSERT INTO product (id_product,name,price,description) VALUES (151,'at',261,'tortor, dictum');
INSERT INTO product (id_product,name,price,description) VALUES (152,'orci',234,'eu, ligula. Aenean euismod mauris');
INSERT INTO product (id_product,name,price,description) VALUES (153,'in',846,'Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
INSERT INTO product (id_product,name,price,description) VALUES (154,'Duis',585,'lobortis risus. In mi pede, nonummy');
INSERT INTO product (id_product,name,price,description) VALUES (155,'eu',178,'viverra. Maecenas iaculis aliquet diam. Sed');
INSERT INTO product (id_product,name,price,description) VALUES (156,'semper',393,'vulputate, nisi sem');
INSERT INTO product (id_product,name,price,description) VALUES (157,'ac',737,'Pellentesque ut ipsum ac');
INSERT INTO product (id_product,name,price,description) VALUES (158,'sapien.',449,'enim nec tempus scelerisque, lorem ipsum sodales purus, in');
INSERT INTO product (id_product,name,price,description) VALUES (159,'Nulla',489,'mauris eu elit. Nulla');
INSERT INTO product (id_product,name,price,description) VALUES (160,'ultricies',926,'Mauris molestie pharetra nibh. Aliquam');
INSERT INTO product (id_product,name,price,description) VALUES (161,'nulla',793,'viverra. Maecenas iaculis aliquet diam. Sed');
INSERT INTO product (id_product,name,price,description) VALUES (162,'non,',486,'viverra. Donec tempus, lorem fringilla ornare placerat, orci');
INSERT INTO product (id_product,name,price,description) VALUES (163,'consectetuer',378,'sit amet, dapibus');
INSERT INTO product (id_product,name,price,description) VALUES (164,'arcu.',834,'consectetuer');
INSERT INTO product (id_product,name,price,description) VALUES (165,'elit,',636,'senectus et netus et');
INSERT INTO product (id_product,name,price,description) VALUES (166,'lacus.',653,'primis in faucibus orci luctus et ultrices posuere cubilia Curae;');
INSERT INTO product (id_product,name,price,description) VALUES (167,'ante.',1041,'ac mattis velit justo nec ante. Maecenas mi felis,');
INSERT INTO product (id_product,name,price,description) VALUES (168,'et,',1187,'enim. Sed nulla ante, iaculis nec,');
INSERT INTO product (id_product,name,price,description) VALUES (169,'adipiscing',863,'Nullam vitae diam. Proin dolor. Nulla semper tellus id');
INSERT INTO product (id_product,name,price,description) VALUES (170,'Vivamus',668,'a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras');
INSERT INTO product (id_product,name,price,description) VALUES (171,'egestas',670,'rutrum. Fusce dolor');
INSERT INTO product (id_product,name,price,description) VALUES (172,'sit',349,'consectetuer adipiscing elit. Etiam laoreet, libero et tristique');
INSERT INTO product (id_product,name,price,description) VALUES (173,'tortor.',1080,'non, lobortis quis, pede. Suspendisse dui.');
INSERT INTO product (id_product,name,price,description) VALUES (174,'ac',664,'pellentesque massa');
INSERT INTO product (id_product,name,price,description) VALUES (175,'nisi',214,'mauris.');
INSERT INTO product (id_product,name,price,description) VALUES (176,'turpis',1144,'placerat velit. Quisque varius. Nam porttitor scelerisque');
INSERT INTO product (id_product,name,price,description) VALUES (177,'eu',339,'semper egestas, urna justo faucibus lectus, a sollicitudin orci');
INSERT INTO product (id_product,name,price,description) VALUES (178,'auctor',232,'neque. Sed eget lacus. Mauris');
INSERT INTO product (id_product,name,price,description) VALUES (179,'Pellentesque',132,'primis in faucibus orci luctus et ultrices posuere');
INSERT INTO product (id_product,name,price,description) VALUES (180,'Sed',570,'vitae aliquam eros turpis non enim. Mauris quis turpis');
INSERT INTO product (id_product,name,price,description) VALUES (181,'at,',837,'congue turpis. In condimentum. Donec at arcu.');
INSERT INTO product (id_product,name,price,description) VALUES (182,'nunc',538,'Nulla interdum.');
INSERT INTO product (id_product,name,price,description) VALUES (183,'nec',501,'semper egestas, urna justo faucibus lectus, a sollicitudin');
INSERT INTO product (id_product,name,price,description) VALUES (184,'neque',1015,'magna tellus faucibus leo, in lobortis tellus');
INSERT INTO product (id_product,name,price,description) VALUES (185,'mi',1161,'nunc. Quisque ornare tortor at risus. Nunc ac');
INSERT INTO product (id_product,name,price,description) VALUES (186,'turpis.',757,'mollis nec, cursus a, enim. Suspendisse aliquet, sem ut');
INSERT INTO product (id_product,name,price,description) VALUES (187,'mattis.',891,'elementum, lorem ut');
INSERT INTO product (id_product,name,price,description) VALUES (188,'magna.',247,'felis purus ac tellus.');
INSERT INTO product (id_product,name,price,description) VALUES (189,'dolor',646,'accumsan neque et');
INSERT INTO product (id_product,name,price,description) VALUES (190,'nisi',908,'laoreet');
INSERT INTO product (id_product,name,price,description) VALUES (191,'erat.',929,'varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada');
INSERT INTO product (id_product,name,price,description) VALUES (192,'in',205,'pharetra,');
INSERT INTO product (id_product,name,price,description) VALUES (193,'Sed',306,'massa lobortis ultrices. Vivamus');
INSERT INTO product (id_product,name,price,description) VALUES (194,'vitae,',839,'Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum.');
INSERT INTO product (id_product,name,price,description) VALUES (195,'rutrum,',380,'euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit');
INSERT INTO product (id_product,name,price,description) VALUES (196,'molestie',647,'parturient montes, nascetur ridiculus mus. Proin vel');
INSERT INTO product (id_product,name,price,description) VALUES (197,'vitae',270,'ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus');
INSERT INTO product (id_product,name,price,description) VALUES (198,'nec',1181,'sed pede. Cum');
INSERT INTO product (id_product,name,price,description) VALUES (199,'ridiculus',383,'gravida');
INSERT INTO product (id_product,name,price,description) VALUES (200,'conubia',286,'lacus. Ut nec urna et arcu imperdiet ullamcorper.');
